config: {}
jaffle_shop:
  outputs:
    dev:
      keyfile_json:
        auth_provider_x509_cert_url: auth_provider_x509_cert_url
        auth_uri: auth_uri
        client_email: client_email
        client_id: client_id
        client_x509_cert_url: client_x509_cert_url
        private_key: private_key
        private_key_id: private_key_id
        project_id: project_id
        token_uri: token_uri
        type: service_account
      method: service-account-json
      project: project
      schema: schema
      threads: 4
      type: gcp
  target: dev
